export const ACTIONS = {
    COOL_INCREMENT_SMALL: 0,
    COOL_DECREMENT_SMALL: 1,
    FAN_INCREMENT_SMALL: 2,
    COOL_INCREMENT_LARGE: 3,
    COOL_DECREMENT_LARGE: 4,
    FAN_INCREMENT_LARGE: 5,
    MAINTAIN: 6,
    THERMAL_STORAGE_CHARGE: 7,
    THERMAL_STORAGE_DISCHARGE: 8
  };
  
  export const MAX_DATA_POINTS = 300;